version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
    container_name: app
    expose:
      - 9000
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - pgsql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/laravel
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  pgsql:
    image: postgres:9.6
    container_name: pgsql
    ports:
      - "5431:5432"
    environment:
      - "POSTGRES_PASSWORD=app"
      - "POSTGRES_USER=app"
      - "POSTGRES_DB=app"
    volumes:
      - pgsql-data:/var/lib/postgresql/data

volumes:
  pgsql-data:
